language: ruby
cache:
  - bundler
bundler_args: --jobs 1 --retry 5 --without development --path vendor/bundle
rvm:
  - 2.2.4
  - 2.3
matrix:
  fast_finish: true
branches:
  only:
    - master
script: bundle exec rake test
